Update patch set 1
Patch Set 1: I would prefer that you didn't submit this

urllib2.HTTPError: HTTP Error 403: Forbidden - is due to a github api limitation, they recently reduced the number of requests allowed.

Cherry-picking the commit AndroidMeda linked would help.

Patch-set: 1